<?xml version="1.0" encoding="utf-8"?><Database Name="PersonasDB" Class="PersonasDataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=JARVIS;Initial Catalog=PersonasDB;Integrated Security=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="PersonasConnectString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Personas" Member="Personas">
    <Type Name="Personas">
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
  <Function Name="dbo.Cons_Personas" Method="Cons_Personas">
    <ElementType Name="Cons_PersonasResult">
      <Column Name="Cedula" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Nombre" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Telefono" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Direccion" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Correo" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
    </ElementType>
  </Function>
  <Function Name="dbo.Ins_Personas" Method="Ins_Personas">
    <Parameter Name="Cedula" Parameter="cedula" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Nombre" Parameter="nombre" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Telefono" Parameter="telefono" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Direccion" Parameter="direccion" Type="System.String" DbType="NVarChar(50)" />
    <Parameter Name="Correo" Parameter="correo" Type="System.String" DbType="NVarChar(50)" />
    <Return Type="System.Int32" />
  </Function>
</Database>